apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: platform-demo
spec:
  ingressClassName: traefik
  rules:
    - host: whoami.k3s-lab.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
