all:
  children:
    k3s_cluster:
      vars:
        ansible_become: true
        ansible_user: ubuntu
        k3s_version: v1.37.1+k3s1
        k3s_install_script_commit: 356c025475bbefaa09cf0d7e48e8e2adbbde57db
        k3s_install_script_sha256: ed01f89fd977bf20ac1516bbebf8370bf3ddbaa55dac8aba610956a4c78cc00b
        k3s_api_endpoint_ip: 10.77.0.1
        k3s_api_endpoint: "https://{{ k3s_api_endpoint_ip }}:6443"
        k3s_api_tls_sans:
          - "{{ k3s_api_endpoint_ip }}"
        k3s_install_script_url: "https://raw.githubusercontent.com/k3s-io/k3s/{{ k3s_install_script_commit }}/install.sh"
        k3s_install_script_path: "/usr/local/src/k3s-install-{{ k3s_version | replace('+', '-') }}.sh"
      children:
        k3s_initial:
          hosts:
            k3s-1:
              ansible_host: 10.77.0.11
        k3s_joiners:
          hosts:
            k3s-2:
              ansible_host: 10.77.0.12
            k3s-3:
              ansible_host: 10.77.0.13
